# Generated by Django 5.0.2 on 2024-02-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_custom_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Catagorze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagori_title', models.CharField(max_length=100)),
            ],
        ),
    ]
