# Generated by Django 5.0.2 on 2024-02-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_task_catagorze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_descreption', models.CharField(max_length=500)),
                ('task_priroty', models.CharField(choices=[('Heigh', 'Heigh'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=500)),
                ('task_date', models.DateTimeField(auto_now=True)),
                ('task_categorize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.task_catagorze')),
            ],
        ),
    ]
