# Generated by Django 5.0.2 on 2024-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
