# Generated by Django 5.0.2 on 2024-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_task_model_task_categorize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='otp_token',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
