# Generated by Django 5.0.2 on 2024-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_custom_user_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='task_dates',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
