# Generated by Django 5.0.2 on 2024-02-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_task_model_task_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='task_dates',
        ),
    ]
